(redux) Handle NOEOL files in partitioned text data files
This is a follow-up of PR #385, which introduced a subtle bug that caused a
long line to be sliced off.

Diagnosis:
When InputSplitBase::Read() is requested to read more bytes than available by
all underlying files, the method infers the number of bytes to read using the
file offsets. This logic did not account of the extra newlines to be inserted
by PR #385.

Minimal reproduction:
Create five text files named `test/test_0.libsvm`, `test/test_1.libsvm`,
`test/test_2.libsvm`, `test/test_3.libsvm`, `test/test_4.libsvm`, each of
which with the content
```
1 3:1 10:1 11:1 21:1 30:1 34:1 36:1 40:1 41:1 53:1 58:1 65:1 69:1 77:1 86:1 88:1 92:1 95:1 102:1 105:1 117:1 124:1
```
And then run
```python
dtrain = xgboost.DMatrix('test')
```

Expected output:
```
5x125 matrix with 110 entries loaded from test
```
Actual output:
```
XGBoostError: b'[08:55:48] /Users/chyunsu/Desktop/xgboost/dmlc-core/src/data/./row_block.h:177: Check failed: offset.back() == value.size() || value.size() == 0 \n\nStack trace returned 2 entries:\n[bt] (0) 0   libxgboost.dylib                    0x000000010b06115c dmlc::StackTrace[abi:cxx11]() + 364\n[bt] (1) 1   libstdc++.6.dylib                   0x000000010b48ef80 vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> > + 16\n\n
```