Add build support for cygwin
1. use std::fopen instead of fopen64 under cygwin
2. add a variable to support --gnu++11, this is to fix error: "fileno was not declared in this scope"
3. turn off DMLC_LOG_STACK_TRACE under cygwin to fix error: "execinfo.h: No such file or directory"